//! Low-level autogenerated FFI bindings over `parakeet_capi.h` from
//! [mudler/parakeet.cpp](https://github.com/mudler/parakeet.cpp).
//!
//! Most users should depend on the higher-level [`parakeet-cpp`](../parakeet_cpp/index.html)
//! crate, which provides a safe, ergonomic Rust API over these raw bindings.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn abi_version_is_known() {
        // SAFETY: parameterless C function with no side effects.
        let v = unsafe { parakeet_capi_abi_version() };
        assert!(v >= 4, "expected ABI >= 4, got {v}");
    }
}
